# Generated by Django 6.0.7 on 2026-07-30 18:05

import django.db.models.deletion
import modelcluster.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0002_product_menu_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Simulator hanya tampil ketika aktif dan seluruh konfigurasi wajib lengkap.')),
                ('product_kind', models.CharField(choices=[('savings', 'Simpanan'), ('loan', 'Pinjaman')], max_length=20)),
                ('strategy', models.CharField(choices=[('savings_simple', 'Simpanan bunga sederhana'), ('savings_compound', 'Simpanan bunga majemuk'), ('savings_recurring', 'Simpanan rutin'), ('loan_flat', 'Pinjaman bunga flat'), ('loan_declining', 'Pinjaman pokok tetap / bunga menurun'), ('loan_annuity', 'Pinjaman anuitas'), ('loan_bullet', 'Pinjaman pokok dibayar di akhir')], max_length=40)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_default', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_step', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tenor_mode', models.CharField(choices=[('range', 'Rentang tenor'), ('options', 'Pilihan tenor tertentu')], default='range', max_length=20)),
                ('tenor_min_months', models.PositiveIntegerField(blank=True, null=True)),
                ('tenor_max_months', models.PositiveIntegerField(blank=True, null=True)),
                ('tenor_default_months', models.PositiveIntegerField(blank=True, null=True)),
                ('tenor_step_months', models.PositiveIntegerField(default=1)),
                ('tenor_options', models.JSONField(blank=True, default=list, help_text='Daftar angka bulan, misalnya [3, 6, 12]. Dipakai hanya untuk mode pilihan tenor.')),
                ('recurring_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('recurring_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('recurring_default', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('recurring_step', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_timing', models.CharField(choices=[('beginning', 'Awal periode'), ('end', 'Akhir periode')], default='beginning', max_length=20)),
                ('rate_mode', models.CharField(choices=[('fixed', 'Bunga tetap'), ('tiered', 'Bunga berdasarkan tier')], default='fixed', max_length=20)),
                ('base_annual_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Persentase per tahun. Contoh: 6.5 berarti 6,5% p.a.', max_digits=9, null=True)),
                ('rate_application', models.CharField(choices=[('locked_at_start', 'Dikunci dari nominal awal dan tenor'), ('current_balance', 'Dievaluasi dari saldo setiap periode'), ('progressive', 'Progresif per lapisan saldo')], default='locked_at_start', max_length=30)),
                ('breakdown_mode', models.CharField(choices=[('auto_compact', 'Otomatis ringkas (maks. 12 baris)'), ('auto_detailed', 'Otomatis detail (maks. 20 baris)'), ('fixed', 'Interval tetap'), ('custom', 'Aturan tenor custom')], default='auto_compact', max_length=30)),
                ('fixed_breakdown_months', models.PositiveIntegerField(choices=[(1, 'Bulanan'), (3, 'Triwulanan'), (6, 'Semester'), (12, 'Tahunan'), (24, 'Dua tahunan')], default=1)),
                ('show_chart', models.BooleanField(default=True)),
                ('show_table', models.BooleanField(default=True)),
                ('simulator_title', models.CharField(blank=True, default='Simulasikan produk ini', max_length=160)),
                ('simulator_description', models.TextField(blank=True, default='Atur nominal dan tenor untuk melihat estimasi hasil beserta rinciannya.')),
                ('disclaimer', models.TextField(blank=True, default='Hasil simulasi merupakan estimasi dan bukan penawaran atau persetujuan final. Nilai aktual mengikuti verifikasi dan ketentuan koperasi.')),
                ('advanced_config', models.JSONField(blank=True, default=dict, help_text='Cadangan konfigurasi tervalidasi untuk strategy khusus; bukan formula bebas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='_product.product')),
            ],
            options={
                'verbose_name': 'Product simulator',
                'verbose_name_plural': 'Product simulators',
                'ordering': ('product__title',),
            },
        ),
        migrations.CreateModel(
            name='SimulationBreakdownBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('min_tenor_months', models.PositiveIntegerField(default=1)),
                ('max_tenor_months', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_months', models.PositiveIntegerField(choices=[(1, 'Bulanan'), (3, 'Triwulanan'), (6, 'Semester'), (12, 'Tahunan'), (24, 'Dua tahunan')])),
                ('simulation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_bands', to='_product.productsimulation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('admin', 'Biaya administrasi'), ('provision', 'Provisi'), ('insurance', 'Asuransi'), ('tax', 'Pajak'), ('other', 'Biaya lainnya')], default='admin', max_length=20)),
                ('calculation', models.CharField(choices=[('fixed', 'Nominal tetap'), ('percentage', 'Persentase')], default='fixed', max_length=20)),
                ('basis', models.CharField(choices=[('initial_amount', 'Nominal awal'), ('opening_balance', 'Saldo awal periode'), ('interest', 'Bunga periode'), ('payment', 'Pembayaran periode'), ('total_interest', 'Total bunga')], default='initial_amount', max_length=30)),
                ('timing', models.CharField(choices=[('upfront', 'Di awal'), ('per_period', 'Setiap periode'), ('maturity', 'Saat jatuh tempo')], default='upfront', max_length=20)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('simulation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='_product.productsimulation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationRateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Angka lebih besar dipilih lebih dahulu saat aturan overlap.')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('min_tenor_months', models.PositiveIntegerField(default=1)),
                ('max_tenor_months', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('simulation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_tiers', to='_product.productsimulation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='productsimulation',
            constraint=models.CheckConstraint(condition=models.Q(('base_annual_rate__isnull', True), ('base_annual_rate__gte', 0), _connector='OR'), name='product_sim_base_rate_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productsimulation',
            constraint=models.CheckConstraint(condition=models.Q(('tenor_step_months__gt', 0)), name='product_sim_tenor_step_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='simulationfeerule',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='sim_fee_rule_value_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='simulationratetier',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gte', 0)), name='sim_rate_tier_min_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='simulationratetier',
            constraint=models.CheckConstraint(condition=models.Q(('annual_rate__gte', 0)), name='sim_rate_tier_rate_gte_zero'),
        ),
    ]
