# Generated by Django 6.0.5 on 2026-07-31 05:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0003_productsimulation_simulationbreakdownband_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_id', models.CharField(editable=False, max_length=80, unique=True)),
                ('booking_number', models.CharField(editable=False, max_length=80, unique=True)),
                ('is_new_member', models.BooleanField(default=False, help_text='Check if this person is a new member. New members do not need a nomor anggota.')),
                ('nomor_anggota', models.CharField(blank=True, help_text='Required for existing members. Leave blank for new members.', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(help_text='WhatsApp number (required).', max_length=24, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9\\s-]{7,19}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(max_length=254)),
                ('nik', models.CharField(blank=True, help_text='Optional — 16-digit NIK.', max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'NIK must contain exactly 16 digits.')])),
                ('note', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('creating', 'Creating payment'), ('waiting_payment', 'Waiting for payment'), ('paid', 'Paid'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='creating', max_length=24)),
                ('xendit_session_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('xendit_session_status', models.CharField(blank=True, max_length=32)),
                ('payment_link_url', models.URLField(blank=True, max_length=500)),
                ('session_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payment_request_id', models.CharField(blank=True, max_length=100)),
                ('xendit_webhook_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('xendit_create_response', models.JSONField(blank=True, default=dict)),
                ('xendit_last_response', models.JSONField(blank=True, default=dict)),
                ('xendit_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('email_last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The savings product this transaction belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='saving_transactions', to='_product.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'status'], name='saving_tx_product_status'), models.Index(fields=['reference_id', 'status'], name='saving_tx_ref_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='saving_tx_amount_gte_zero'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='saving_tx_total_gte_zero')],
            },
        ),
    ]
