# Generated by Django 6.0.5 on 2026-07-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0004_savingtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingtransaction',
            old_name='booking_number',
            new_name='transaction_code',
        ),
    ]
