# Generated by Django 6.0.5 on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_product", "0005_rename_booking_number_savingtransaction_transaction_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savingtransaction",
            name="payment_channel",
            field=models.CharField(
                choices=[
                    ("xendit", "Online via Xendit"),
                    ("manual", "Setoran manual oleh admin"),
                ],
                db_index=True,
                default="xendit",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="savingtransaction",
            name="manual_reference",
            field=models.CharField(
                blank=True,
                help_text="Nomor bukti setoran/transfer untuk transaksi manual (opsional).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="savingtransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_saving_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="savingtransaction",
            name="product",
            field=models.ForeignKey(
                help_text="The savings product this transaction belongs to.",
                limit_choices_to={"category__slug": "simpanan"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saving_transactions",
                to="_product.product",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="savingtransaction",
            name="saving_tx_amount_gte_zero",
        ),
        migrations.AddConstraint(
            model_name="savingtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="saving_tx_amount_gt_zero",
            ),
        ),
    ]
