# Generated by Django 6.0.7 on 2026-08-01 18:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_p2p', '0006_p2pseosettings_list_heading_and_intro'),
        ('_product', '0007_alter_savingtransaction_payment_channel'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XenditPaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('virtual_account', 'Virtual Account')], default='virtual_account', max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_for_saving', models.BooleanField(default=True)),
                ('enabled_for_p2p', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xendit_payment_channels',
                'verbose_name': 'Kanal pembayaran Xendit',
                'verbose_name_plural': 'Kanal pembayaran Xendit',
                'ordering': ('sort_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='XenditReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Berjalan'), ('completed', 'Selesai'), ('completed_with_errors', 'Selesai dengan error'), ('failed', 'Gagal')], default='running', max_length=32)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('variance_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'xendit_reconciliation_runs',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='XenditFeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gunakan nilai positif untuk menutup kekurangan dan negatif untuk koreksi kelebihan.', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('kind', models.CharField(choices=[('provider_credit', 'Kredit Xendit'), ('provider_debit', 'Debit Xendit'), ('ks3_subsidy', 'Subsidi KS3'), ('manual_correction', 'Koreksi manual'), ('reversal', 'Reversal')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Disetujui'), ('posted', 'Posted'), ('reversed', 'Dibatalkan')], default='draft', max_length=20)),
                ('reason', models.TextField()),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_xendit_fee_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_xendit_fee_adjustments', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xendit_fee_adjustments', to='wagtaildocs.document')),
            ],
            options={
                'db_table': 'xendit_fee_adjustments',
                'verbose_name': 'Adjustment fee Xendit',
                'verbose_name_plural': 'Adjustment fee Xendit',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='XenditFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('percentage_fee', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Persentase dari nominal pokok, misalnya 1.5000 untuk 1,5%.', max_digits=8)),
                ('vat_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Persentase VAT/PPN atas fee provider.', max_digits=6)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual/kontrak'), ('observed', 'Terdeteksi dari transaksi'), ('legacy', 'Migrasi tarif lama')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Aktif'), ('superseded', 'Digantikan')], default='active', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('observed_transaction_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_rates', to='_payment.xenditpaymentchannel')),
            ],
            options={
                'db_table': 'xendit_fee_rates',
                'verbose_name': 'Versi tarif Xendit',
                'verbose_name_plural': 'Versi tarif Xendit',
                'ordering': ('channel', '-effective_from'),
            },
        ),
        migrations.CreateModel(
            name='XenditTransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charged_fee_before_tax', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charged_fee_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('charged_fee_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_snapshot', models.JSONField(default=dict)),
                ('allowed_payment_channels', models.JSONField(default=list)),
                ('session_request_snapshot', models.JSONField(default=dict)),
                ('session_response_snapshot', models.JSONField(default=dict)),
                ('xendit_session_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_product_id', models.CharField(blank=True, max_length=120)),
                ('provider_payment_request_id', models.CharField(blank=True, max_length=120)),
                ('provider_reference_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_transaction_type', models.CharField(blank=True, max_length=40)),
                ('provider_transaction_status', models.CharField(blank=True, max_length=32)),
                ('provider_business_id', models.CharField(blank=True, max_length=120)),
                ('actual_channel_category', models.CharField(blank=True, max_length=40)),
                ('actual_channel_code', models.CharField(blank=True, max_length=80)),
                ('actual_currency', models.CharField(blank=True, max_length=3)),
                ('account_identifier', models.CharField(blank=True, max_length=255)),
                ('cashflow', models.CharField(blank=True, max_length=24)),
                ('actual_net_amount_currency', models.CharField(blank=True, max_length=3)),
                ('actual_gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_xendit_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_xendit_withholding_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_third_party_withholding_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_fee_status', models.CharField(blank=True, max_length=24)),
                ('settlement_status', models.CharField(blank=True, max_length=24)),
                ('provider_created_at', models.DateTimeField(blank=True, null=True)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_settlement_at', models.DateTimeField(blank=True, null=True)),
                ('actual_product_data', models.JSONField(default=dict)),
                ('actual_payload', models.JSONField(default=dict)),
                ('reconciliation_status', models.CharField(choices=[('pending', 'Menunggu actual fee'), ('matched', 'Sesuai'), ('short', 'Kurang'), ('over', 'Lebih'), ('adjusted', 'Sudah disesuaikan'), ('missing', 'Transaksi provider belum ditemukan'), ('review', 'Perlu review')], db_index=True, default='pending', max_length=20)),
                ('reconciliation_attempts', models.PositiveIntegerField(default=0)),
                ('reconciliation_last_error', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fees', to='_payment.xenditpaymentchannel')),
                ('p2p_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xendit_fee_snapshot', to='_p2p.p2ppurchase')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fees', to='_payment.xenditfeerate')),
                ('saving_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xendit_fee_snapshot', to='_product.savingtransaction')),
            ],
            options={
                'db_table': 'xendit_fees',
                'verbose_name': 'Snapshot fee transaksi Xendit',
                'verbose_name_plural': 'Snapshot fee transaksi Xendit',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='XenditFeeAdjustmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='_payment.xenditfeeadjustment')),
                ('transaction_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_allocations', to='_payment.xendittransactionfee')),
            ],
            options={
                'db_table': 'xendit_fee_adjustment_allocations',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='xenditfeeadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='payment_fee_adjustment_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='xenditfeerate',
            constraint=models.UniqueConstraint(fields=('channel', 'currency', 'effective_from'), name='payment_fee_rate_channel_currency_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='xenditfeerate',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_fee__gte', 0)), name='payment_fee_rate_fixed_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='xenditfeerate',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_fee__gte', 0)), name='payment_fee_rate_percentage_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='xenditfeerate',
            constraint=models.CheckConstraint(condition=models.Q(('vat_percent__gte', 0)), name='payment_fee_rate_vat_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='xendittransactionfee',
            index=models.Index(fields=['reconciliation_status', 'created_at'], name='payment_fee_recon_created'),
        ),
        migrations.AddIndex(
            model_name='xendittransactionfee',
            index=models.Index(fields=['actual_channel_code', 'reconciled_at'], name='payment_fee_channel_recon'),
        ),
        migrations.AddConstraint(
            model_name='xendittransactionfee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('saving_transaction__isnull', False), ('p2p_purchase__isnull', True)), models.Q(('saving_transaction__isnull', True), ('p2p_purchase__isnull', False)), _connector='OR'), name='payment_fee_exactly_one_transaction'),
        ),
        migrations.AddConstraint(
            model_name='xendittransactionfee',
            constraint=models.CheckConstraint(condition=models.Q(('charged_fee_total__gte', 0)), name='payment_fee_charged_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='xenditfeeadjustmentallocation',
            constraint=models.UniqueConstraint(fields=('adjustment', 'transaction_fee'), name='payment_fee_adjustment_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='xenditfeeadjustmentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='payment_fee_allocation_non_zero'),
        ),
    ]
