# Generated by Django 6.0.5 on 2026-07-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneouspage',
            name='menu_description',
            field=models.CharField(blank=True, help_text='Very short description for the header dropdown (3–5 words).', max_length=60),
        ),
    ]
