# Generated by Django 6.0.5 on 2026-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_host_password', models.CharField(blank=True, help_text='Use an App Password when using Gmail.', max_length=255, null=True)),
                ('reverify_cooldown_minutes', models.PositiveIntegerField(default=2, help_text='Cooldown in minutes before a verification link can be resent.')),
                ('email_confirmation_subject', models.CharField(default='Confirm your email address', max_length=255)),
                ('email_confirmation_html', models.TextField(default='<p>Please confirm your email address.</p>')),
                ('password_reset_subject', models.CharField(default='Reset your password', max_length=255)),
                ('password_reset_html', models.TextField(default='<p>Use the password reset link provided in this email.</p>')),
            ],
            options={
                'verbose_name': 'Email setting',
            },
        ),
        migrations.CreateModel(
            name='XenditSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_url', models.URLField(default='https://api.xendit.co', max_length=255)),
                ('webhook_verification_token', models.CharField(blank=True, max_length=255)),
                ('public_base_url', models.URLField(blank=True, help_text='Public HTTPS base URL used for Xendit return URLs (for example the ngrok URL).')),
                ('session_duration', models.PositiveIntegerField(default=86400, help_text='Payment Session lifetime in seconds; minimum 600.')),
            ],
            options={
                'verbose_name': 'Xendit setting',
            },
        ),
    ]
