# Generated by Django 6.0.5 on 2026-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xenditsetting',
            name='return_base_url',
            field=models.URLField(default='http://127.0.0.1:8000', help_text='Browser return URL after checkout. Localhost is valid for local testing.'),
        ),
        migrations.AlterField(
            model_name='xenditsetting',
            name='public_base_url',
            field=models.URLField(blank=True, help_text='Public HTTPS base URL used by Xendit webhooks (for example the ngrok URL).'),
        ),
    ]
