# Generated by Django 6.0.5 on 2026-07-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0002_xenditsetting_return_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Werkspace Pluit, Jl. Pluit Indah No.168B, Jakarta Utara')),
                ('operational_hours', models.CharField(default='Dukungan Pelanggan (09:00 - 17:00 WIB)', max_length=255)),
                ('whatsapp_display', models.CharField(blank=True, help_text='Nomor yang ditampilkan, contoh: +62 812-3456-7890.', max_length=50)),
                ('whatsapp_link', models.URLField(blank=True, help_text='Tautan WhatsApp lengkap, contoh: https://wa.me/6281234567890.')),
                ('email', models.EmailField(default='cs@koperasiks3.id', max_length=254)),
                ('financing_email', models.EmailField(default='pembiayaan@koperasiks3.id', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact setting',
            },
        ),
    ]
