# Generated by Django 6.0.5 on 2026-07-28 18:46

import _setting.models.homepage
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0003_contactsetting'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_enabled', models.BooleanField(default=True)),
                ('hero_badge', models.CharField(default='Koperasi Simpan Pinjam Berbasis Digital', max_length=160)),
                ('hero_title', models.CharField(default='Simpanan dan Pendanaan UMKM dalam Satu Ekosistem', max_length=255)),
                ('hero_description', models.TextField(default='KS3 menyediakan produk simpanan bagi anggota serta akses P2P Investment untuk mendukung pembiayaan UMKM terverifikasi.')),
                ('hero_primary_label', models.CharField(default='Lihat Produk', max_length=80)),
                ('hero_primary_url', models.CharField(default='/product', max_length=500)),
                ('hero_secondary_label', models.CharField(default='Lihat Investasi P2P', max_length=80)),
                ('hero_secondary_url', models.CharField(default='/peer-to-peer/', max_length=500)),
                ('hero_points', wagtail.fields.StreamField([('item', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {})}, default=_setting.models.homepage.default_hero_points)),
                ('hero_floating_title', models.CharField(default='Produk KSP & P2P', max_length=120)),
                ('hero_floating_description', models.CharField(default='Untuk anggota dan UMKM', max_length=160)),
                ('hero_main_image_alt', models.CharField(default='Layanan digital Koperasi KS3', max_length=160)),
                ('marquee_enabled', models.BooleanField(default=True)),
                ('marquee_items', wagtail.fields.StreamField([('item', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('dark', 'Dark / bold'), ('muted', 'Muted')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('tone', 1)]], {})}, default=_setting.models.homepage.default_marquee_items)),
                ('about_enabled', models.BooleanField(default=True)),
                ('about_badge', models.CharField(default='Tentang KSP KS3', max_length=120)),
                ('about_title', models.CharField(default='Layanan Keuangan Digital bagi Anggota dan UMKM', max_length=255)),
                ('about_description', models.TextField(default='KS3 adalah koperasi simpan pinjam berbasis digital yang membantu anggota mengelola dana sekaligus membuka akses pembiayaan bagi UMKM.')),
                ('about_audiences', wagtail.fields.StreamField([('item', 3)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bi-building-check', 'Building check'), ('bi-wallet2', 'Wallet'), ('bi-shop', 'Shop'), ('bi-phone', 'Phone'), ('bi-graph-up-arrow', 'Growth chart'), ('bi-shield-check', 'Shield check'), ('bi-check-circle-fill', 'Check circle')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 300}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, default=_setting.models.homepage.default_about_audiences)),
                ('about_highlights', wagtail.fields.StreamField([('item', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {})}, default=_setting.models.homepage.default_about_highlights)),
                ('p2p_enabled', models.BooleanField(default=True)),
                ('p2p_small_title', models.CharField(default='P2P Investment', max_length=120)),
                ('p2p_title', models.CharField(default='P2P Investment Pilihan', max_length=255)),
                ('p2p_description', models.TextField(default='Pilih peluang pendanaan UMKM yang sesuai dengan tujuan investasi Anda.')),
                ('products_enabled', models.BooleanField(default=True)),
                ('products_small_title', models.CharField(default='Produk KSP KS3', max_length=120)),
                ('products_title', models.CharField(default='Produk Simpanan untuk Setiap Kebutuhan', max_length=255)),
                ('products_description', models.TextField(default='Mulai dari simpanan keanggotaan, dana fleksibel, hingga simpanan berjangka untuk rencana keuangan Anda.')),
                ('advantages_enabled', models.BooleanField(default=True)),
                ('advantages_badge', models.CharField(default='Keunggulan KS3', max_length=120)),
                ('advantages_title', models.CharField(default='Mengapa Memilih Koperasi KS3?', max_length=255)),
                ('advantages_description', models.TextField(default='KS3 menggabungkan layanan koperasi dengan akses digital untuk membantu anggota mengelola simpanan dan memperoleh pembiayaan secara lebih praktis.')),
                ('advantages_items', wagtail.fields.StreamField([('item', 3)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bi-building-check', 'Building check'), ('bi-wallet2', 'Wallet'), ('bi-shop', 'Shop'), ('bi-phone', 'Phone'), ('bi-graph-up-arrow', 'Growth chart'), ('bi-shield-check', 'Shield check'), ('bi-check-circle-fill', 'Check circle')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 300}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, default=_setting.models.homepage.default_advantages)),
                ('advantages_image_alt', models.CharField(default='Layanan digital Koperasi KS3', max_length=160)),
                ('advantages_floating_title', models.CharField(default='Koperasi Digital', max_length=120)),
                ('advantages_floating_description', models.CharField(default='Untuk anggota dan UMKM', max_length=160)),
                ('faq_enabled', models.BooleanField(default=True)),
                ('faq_badge', models.CharField(default='Pertanyaan Umum', max_length=120)),
                ('faq_title', models.CharField(default='Punya Pertanyaan?', max_length=255)),
                ('faq_description', models.TextField(default='Kami memahami bahwa memilih layanan keuangan adalah keputusan penting. Berikut jawaban atas pertanyaan yang paling sering diajukan oleh calon anggota dan pendana KS3.')),
                ('faq_contact_prefix', models.CharField(default='Untuk pertanyaan lainnya hubungi :', max_length=160)),
                ('faq_support_text', models.CharField(default='Tim kami siap membantu Anda — Senin–Jumat, 09:00–17:00 WIB', max_length=255)),
                ('faq_items', wagtail.fields.StreamField([('item', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 240}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, default=_setting.models.homepage.default_faq_items)),
                ('app_enabled', models.BooleanField(default=True)),
                ('app_image_alt', models.CharField(default='Tampilan aplikasi KS3', max_length=160)),
                ('app_badge', models.CharField(default='Aplikasi KS3', max_length=120)),
                ('app_title', models.CharField(default='KS3, Kini dalam Genggaman Anda', max_length=255)),
                ('app_description', models.TextField(default='Akses informasi pendanaan, pantau peluang P2P, dan dapatkan update KS3 langsung dari aplikasi.')),
                ('app_store_url', models.CharField(default='#', max_length=500)),
                ('play_store_url', models.CharField(default='#', max_length=500)),
                ('about_primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('about_secondary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('advantages_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('app_first_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('app_second_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('faq_support_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_decorative_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('products_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Homepage setting',
            },
        ),
    ]
