# Generated by Django 6.0.5 on 2026-07-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0004_homepagesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesetting',
            name='faq_support_image',
        ),
        migrations.RemoveField(
            model_name='homepagesetting',
            name='faq_support_text',
        ),
    ]
