# Generated by Django 6.0.7 on 2026-07-30 19:44

from django.db import migrations, models


OLD_COPY = {
    'products_small_title': 'Produk KSP KS3',
    'products_title': 'Produk Simpanan untuk Setiap Kebutuhan',
    'products_description': 'Mulai dari simpanan keanggotaan, dana fleksibel, hingga simpanan berjangka untuk rencana keuangan Anda.',
}
NEW_COPY = {
    'products_small_title': 'Produk Anggota KS3',
    'products_title': 'Simpanan dan Pinjaman untuk Setiap Kebutuhan',
    'products_description': 'Bangun simpanan sesuai tujuan atau pilih pembiayaan dengan simulasi pokok, bunga, biaya, dan angsuran yang transparan.',
}


def update_untouched_product_copy(apps, schema_editor):
    HomePageSetting = apps.get_model('_setting', 'HomePageSetting')
    for field, old_value in OLD_COPY.items():
        HomePageSetting.objects.filter(**{field: old_value}).update(
            **{field: NEW_COPY[field]}
        )


def restore_previous_product_copy(apps, schema_editor):
    HomePageSetting = apps.get_model('_setting', 'HomePageSetting')
    for field, new_value in NEW_COPY.items():
        HomePageSetting.objects.filter(**{field: new_value}).update(
            **{field: OLD_COPY[field]}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0005_remove_homepagesetting_faq_support_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesetting',
            name='products_description',
            field=models.TextField(default='Bangun simpanan sesuai tujuan atau pilih pembiayaan dengan simulasi pokok, bunga, biaya, dan angsuran yang transparan.'),
        ),
        migrations.AlterField(
            model_name='homepagesetting',
            name='products_small_title',
            field=models.CharField(default='Produk Anggota KS3', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepagesetting',
            name='products_title',
            field=models.CharField(default='Simpanan dan Pinjaman untuk Setiap Kebutuhan', max_length=255),
        ),
        migrations.RunPython(
            update_untouched_product_copy,
            restore_previous_product_copy,
        ),
    ]
