# Generated by Django 6.0.7 on 2026-08-01 18:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0010_contactsetting_whatsapp_floating_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='xenditsetting',
            name='auto_learn_va_fees',
            field=models.BooleanField(default=True, help_text='Buat versi tarif VA baru dari actual fee Xendit untuk transaksi berikutnya.'),
        ),
        migrations.AddField(
            model_name='xenditsetting',
            name='fee_auto_update_max_delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), help_text='Perubahan di atas nominal ini ditahan sebagai candidate untuk review admin.', max_digits=18),
        ),
    ]
