# Generated by Django 6.0.7 on 2026-08-01 18:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_setting', '0011_xenditsetting_auto_learn_va_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xenditsetting',
            name='saving_payment_gateway_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('2750'), help_text='Legacy only; tarif transaksi baru dikelola pada Versi Tarif VA.', max_digits=18),
        ),
    ]
