import logging
from datetime import datetime
from decimal import Decimal
from urllib.parse import urlparse

from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction
from django.urls import reverse
from django.utils import timezone

from backend.services.xendit import XenditService
from _payment.services import create_fee_snapshot, resolve_fee
from _product.models import SavingTransaction
from _setting.models import XenditSetting


logger = logging.getLogger(__name__)


class SavingWorkflowError(Exception):
    pass


def _configured_return_url(saving_txn):
    base_url = XenditSetting.load().return_base_url.rstrip("/")
    parsed = urlparse(base_url)
    if parsed.scheme != "https" or not parsed.netloc:
        logger.warning(
            "Saving Xendit return URL is disabled because return_base_url is not HTTPS: %s",
            base_url,
        )
        return ""
    path = reverse("saving_xendit_return", kwargs={"public_id": saving_txn.public_id})
    return f"{base_url}{path}"


def create_saving_transaction(*, saving_txn):
    """
    Creates a Xendit invoice for an already-saved SavingTransaction instance.
    Identifiers and total_amount are auto-generated by the model's save().
    """
    try:
        try:
            fee_snapshot = saving_txn.xendit_fee_snapshot
        except ObjectDoesNotExist:
            resolved = resolve_fee(
                channel_code=None,
                route="saving",
                principal_amount=saving_txn.amount,
            )
            if resolved.total_fee != saving_txn.service_fee:
                raise SavingWorkflowError(
                    "Biaya transaksi tidak sama dengan tarif VA aktif; buat ulang transaksi."
                )
            fee_snapshot, _ = create_fee_snapshot(
                transaction=saving_txn,
                route="saving",
                channel_code=resolved.channel.code,
                principal_amount=saving_txn.amount,
                resolved=resolved,
            )
        if (
            fee_snapshot.principal_amount != saving_txn.amount
            or fee_snapshot.charged_fee_total != saving_txn.service_fee
        ):
            raise SavingWorkflowError(
                "Snapshot fee tidak sama dengan nominal transaksi; transaksi diblokir."
            )
        return_url = _configured_return_url(saving_txn)
        return_kwargs = {}
        if return_url:
            return_kwargs = {
                "success_return_url": return_url,
                "cancel_return_url": return_url,
            }
        items = [
            {
                "reference_id": f"{saving_txn.reference_id}-principal",
                "type": "DIGITAL_SERVICE",
                "name": f"Setoran {saving_txn.product.title}"[:255],
                "net_unit_amount": int(saving_txn.amount),
                "quantity": 1,
            }
        ]
        if saving_txn.service_fee:
            items.append(
                {
                    "reference_id": f"{saving_txn.reference_id}-fee",
                    "type": "FEE",
                    "name": "Biaya administrasi pembayaran",
                    "net_unit_amount": int(saving_txn.service_fee),
                    "quantity": 1,
                }
            )
        session_kwargs = {
            "reference_id": saving_txn.reference_id,
            "amount": saving_txn.total_amount,
            "description": f"Setoran Simpanan {saving_txn.product.title} ({saving_txn.transaction_code})",
            "currency": saving_txn.currency,
            "allowed_payment_channels": fee_snapshot.allowed_payment_channels,
            "items": items,
            "metadata": {
                "route": "saving",
                "transaction_reference": saving_txn.reference_id,
                "transaction_code": saving_txn.transaction_code,
                "fee_snapshot_id": str(fee_snapshot.pk),
                "fee_rate_version": str(fee_snapshot.rate_id),
                "selected_va_channel": fee_snapshot.channel.code,
                "principal_amount": str(saving_txn.amount),
                "charged_fee_total": str(saving_txn.service_fee),
                "charged_total_amount": str(saving_txn.total_amount),
            },
            **return_kwargs,
        }
        fee_snapshot.session_request_snapshot = {
            **session_kwargs,
            "amount": str(saving_txn.total_amount),
            "items": [
                {**item, "net_unit_amount": str(item["net_unit_amount"])} for item in items
            ],
        }
        fee_snapshot.save(update_fields=("session_request_snapshot", "updated_at"))
        response = XenditService.create_invoice(
            **session_kwargs,
        )
        required = ("payment_session_id", "reference_id", "status", "payment_link_url", "expires_at")
        missing = [field for field in required if not response.get(field)]
        if missing:
            raise SavingWorkflowError(f"Xendit response is missing: {', '.join(missing)}.")
        if response["reference_id"] != saving_txn.reference_id:
            raise SavingWorkflowError("Xendit returned a different reference ID.")

        saving_txn.xendit_session_id = response["payment_session_id"]
        saving_txn.xendit_session_status = response["status"]
        saving_txn.payment_link_url = response["payment_link_url"]
        saving_txn.session_expires_at = datetime.fromisoformat(
            response["expires_at"].replace("Z", "+00:00")
        )
        saving_txn.xendit_create_response = response
        saving_txn.xendit_last_response = response
        saving_txn.status = SavingTransaction.Status.WAITING_PAYMENT
        saving_txn.save()
        fee_snapshot.xendit_session_id = response["payment_session_id"]
        fee_snapshot.session_response_snapshot = response
        fee_snapshot.save(
            update_fields=(
                "xendit_session_id",
                "session_response_snapshot",
                "updated_at",
            )
        )
        return saving_txn
    except Exception:
        saving_txn.status = SavingTransaction.Status.FAILED
        saving_txn.save(update_fields=("status", "updated_at"))
        raise


def create_online_saving_transaction(**values):
    """Persist a validated public saving request and create its Xendit session."""
    amount = Decimal(values.pop("amount"))
    channel_code = values.pop("xendit_channel", None)
    values.pop("service_fee", None)
    resolved = resolve_fee(
        channel_code=channel_code,
        route="saving",
        principal_amount=amount,
    )
    service_fee = resolved.total_fee
    with transaction.atomic():
        saving_txn = SavingTransaction(
            **values,
            amount=amount,
            service_fee=service_fee,
            total_amount=amount + service_fee,
            payment_channel=SavingTransaction.PaymentChannel.XENDIT,
            status=SavingTransaction.Status.CREATING,
        )
        saving_txn.full_clean()
        saving_txn.save()
        create_fee_snapshot(
            transaction=saving_txn,
            route="saving",
            channel_code=resolved.channel.code,
            principal_amount=amount,
            resolved=resolved,
        )
    return create_saving_transaction(saving_txn=saving_txn)


@transaction.atomic
def record_manual_saving_transaction(saving_txn, *, recorded_by=None):
    """Finalize a backend-entered setoran without creating a Xendit session."""
    saving_txn = SavingTransaction.objects.select_for_update().get(pk=saving_txn.pk)
    paid_at = timezone.now()
    saving_txn.payment_channel = SavingTransaction.PaymentChannel.MANUAL
    saving_txn.status = SavingTransaction.Status.PAID
    saving_txn.paid_at = paid_at
    saving_txn.provider_updated_at = paid_at
    saving_txn.xendit_session_status = "MANUAL"
    saving_txn.created_by = recorded_by
    saving_txn.full_clean()
    saving_txn.save()

    from .email_notification import send_saving_paid_email_safely

    transaction.on_commit(lambda: send_saving_paid_email_safely(saving_txn.pk))
    return saving_txn
