# Generated by Django 6.0.5 on 2026-07-28 17:16

import django.core.validators
import django.db.models.deletion
import uuid
import wagtail.fields
import wagtail.models.preview
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'P2P categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='P2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('summary', models.TextField()),
                ('content', wagtail.fields.StreamField([('heading', 2), ('paragraph', 4), ('two_column_text', 5), ('image', 9), ('two_column_image', 12), ('image_text', 14), ('list', 18), ('manual_table', 23), ('blockquote', 26), ('accordion', 30), ('document', 33), ('video', 35), ('separator', 36), ('spacing', 38)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 2: ('wagtail.blocks.StructBlock', [[('level', 0), ('title', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul']}), 4: ('wagtail.blocks.StructBlock', [[('content', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('left', 3), ('right', 3)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('alt_text', 7), ('caption', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Left image'}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Right image'}), 12: ('wagtail.blocks.StructBlock', [[('left_image', 10), ('left_alt_text', 7), ('right_image', 11), ('right_alt_text', 7)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right')]}), 14: ('wagtail.blocks.StructBlock', [[('image', 6), ('image_position', 13), ('title', 7), ('content', 3)]], {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('unordered', 'Bullet list'), ('ordered', 'Numbered list')]}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 17: ('wagtail.blocks.ListBlock', (16,), {'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('style', 15), ('items', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 20: ('wagtail.blocks.ListBlock', (19,), {'min_num': 1}), 21: ('wagtail.blocks.StructBlock', [[('cells', 17)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'min_num': 1}), 23: ('wagtail.blocks.StructBlock', [[('title', 7), ('columns', 20), ('rows', 22), ('footer_note', 8)]], {}), 24: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('quote', 24), ('author', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 28: ('wagtail.blocks.StructBlock', [[('title', 27), ('content', 3)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'min_num': 1}), 30: ('wagtail.blocks.StructBlock', [[('items', 29)]], {}), 31: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Download document', 'max_length': 100}), 33: ('wagtail.blocks.StructBlock', [[('document', 31), ('label', 32)]], {}), 34: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube, Vimeo, or another supported URL'}), 35: ('wagtail.blocks.StructBlock', [[('embed', 34), ('caption', 8)]], {}), 36: ('backend.helper.streamfield.SeparatorBlock', (), {}), 37: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('20', 'Small'), ('40', 'Medium'), ('60', 'Large')]}), 38: ('wagtail.blocks.StructBlock', [[('size', 37)]], {})})),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('slot_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('2750'), max_digits=18)),
                ('total_slots', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tenor_months', models.PositiveIntegerField()),
                ('installment_frequency', models.CharField(choices=[('monthly', 'Bulanan'), ('quarterly', 'Triwulanan'), ('end_of_term', 'Di akhir tenor')], default='monthly', max_length=20)),
                ('funding_deadline', models.DateTimeField()),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('collateral', models.CharField(blank=True, default='Tidak ada', max_length=255)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospectus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='_p2p.p2pcategory')),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='P2PPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_id', models.CharField(editable=False, max_length=80, unique=True)),
                ('booking_number', models.CharField(editable=False, max_length=80, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9\\s-]{7,19}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(max_length=254)),
                ('nik', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'NIK must contain exactly 16 digits.')])),
                ('note', models.TextField(blank=True)),
                ('slot_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('creating', 'Creating payment'), ('waiting_payment', 'Waiting for payment'), ('paid', 'Paid'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='creating', max_length=24)),
                ('xendit_session_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('xendit_session_status', models.CharField(blank=True, max_length=32)),
                ('payment_link_url', models.URLField(blank=True, max_length=500)),
                ('session_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payment_request_id', models.CharField(blank=True, max_length=100)),
                ('xendit_webhook_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('xendit_create_response', models.JSONField(blank=True, default=dict)),
                ('xendit_last_response', models.JSONField(blank=True, default=dict)),
                ('xendit_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='_p2p.p2p')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='P2PSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(blank=True, max_length=255)),
                ('list_description', models.TextField(blank=True)),
                ('list_keywords', models.CharField(blank=True, max_length=255)),
                ('detail_title', models.CharField(blank=True, max_length=255)),
                ('detail_description', models.TextField(blank=True)),
                ('detail_keywords', models.CharField(blank=True, max_length=255)),
                ('purchase_title', models.CharField(blank=True, max_length=255)),
                ('purchase_description', models.TextField(blank=True)),
                ('purchase_keywords', models.CharField(blank=True, max_length=255)),
                ('complete_title', models.CharField(blank=True, max_length=255)),
                ('complete_description', models.TextField(blank=True)),
                ('complete_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'P2P SEO setting',
            },
        ),
        migrations.AddConstraint(
            model_name='p2p',
            constraint=models.CheckConstraint(condition=models.Q(('slot_price__gt', 0)), name='p2p_slot_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='p2p',
            constraint=models.CheckConstraint(condition=models.Q(('total_slots__gt', 0)), name='p2p_total_slots_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='p2p',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='p2p_target_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='p2p',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='p2p_interest_rate_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='p2ppurchase',
            index=models.Index(fields=['project', 'status'], name='p2p_purchase_project_status'),
        ),
        migrations.AddIndex(
            model_name='p2ppurchase',
            index=models.Index(fields=['reference_id', 'status'], name='p2p_purchase_ref_status'),
        ),
        migrations.AddConstraint(
            model_name='p2ppurchase',
            constraint=models.CheckConstraint(condition=models.Q(('slot_quantity__gt', 0)), name='p2p_purchase_slots_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='p2ppurchase',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='p2p_purchase_unit_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='p2ppurchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='p2p_purchase_total_gte_zero'),
        ),
    ]
