# Generated by Django 6.0.5 on 2026-07-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_p2p', '0004_p2ppurchase_email_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p2p',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Proyek', 'verbose_name_plural': 'Proyek'},
        ),
    ]
