# Generated by Django 6.0.5 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("_p2p", "0005_alter_p2p_options")]

    operations = [
        migrations.AddField(
            model_name="p2pseosettings",
            name="list_heading",
            field=models.CharField(
                default="Proyek Anggota",
                max_length=255,
                verbose_name="Judul halaman",
            ),
        ),
        migrations.AddField(
            model_name="p2pseosettings",
            name="list_intro",
            field=models.TextField(
                default="Danai proyek pilihan dan dapatkan imbal hasil yang kompetitif.",
                verbose_name="Teks pengantar",
            ),
        ),
    ]
